### ISSUE TITLE
Dependencies 

### ISSUE THREAD

**Issue by CodyMWilson** [Gregory12100/treevolution#1]
Hey - I got this to run on my system but I have a bunch of libraries pre-installed. @Gregory12100 Can you run pip freeze and send me the output? This will be the basis for the requirements.txt dockerfile.

**Comment by Gregory12100** [comment]
Just one dependency right now anyway: pygame==2.1.2

**Comment by CodyMWilson** [comment]
Cool, thanks! Anything going forward can be added to requirements.txt. One way is to just `pip freeze > requirements.txt`, however I don't like doing this because I've rarely had this work for me without breaking - with lots of dependencies it's likely that one or two won't be recognized by whatever pip version we're running so I usually groom the dependencies by hand.

**Comment by Gregory12100** [comment]
@CodyMWilson FYI, I'm using python 3.10.2 which has some new language features from 3.8.

**Comment by CodyMWilson** [comment]
Nice! I'm running it from python2.7 I believe, because that's what on my machine due to work.
